# Database Configurations
databases:
  sqlite:
    enabled: true
    path: "data/users.db"
    backup_path: "data/backups/"
    backup_schedule: "daily"  # daily, weekly, monthly
    max_backups: 7

  mysql:
    enabled: false
    host: localhost
    port: 3306
    username: ""
    password: ""
    database: ""
    connection_pool: 5
    timeout: 30
    ssl_enabled: false
    charset: "utf8mb4"

  postgresql:
    enabled: false
    host: localhost
    port: 5432
    username: ""
    password: ""
    database: ""
    connection_pool: 5
    timeout: 30
    ssl_mode: "disable"  # disable, require, verify-full
    application_name: "data_analysis_dashboard"

  mongodb:
    enabled: false
    host: localhost
    port: 27017
    username: ""
    password: ""
    database: ""
    auth_source: "admin"
    replica_set: ""
    timeout: 30000
    max_pool_size: 100
    write_concern: 1

# API Configurations
apis:
  rest:
    enabled: true
    base_url: ""
    api_key: ""
    timeout: 30
    retry_attempts: 3
    retry_delay: 1
    rate_limit: 100  # requests per minute
    headers:
      Content-Type: "application/json"
      Accept: "application/json"

  graphql:
    enabled: false
    endpoint: ""
    timeout: 30
    headers: {}
    introspection_enabled: true
    batch_enabled: false

  websocket:
    enabled: false
    url: ""
    protocols: []
    headers: {}
    heartbeat_interval: 30
    reconnect_attempts: 3
    reconnect_delay: 5

# Cache Configurations
cache:
  redis:
    enabled: false
    host: localhost
    port: 6379
    password: ""
    db: 0
    timeout: 5
    encoding: "utf-8"
    compression_enabled: true
    max_memory: "1gb"
    eviction_policy: "allkeys-lru"

  local:
    enabled: true
    path: "cache/"
    max_size: "1gb"
    ttl: 3600  # seconds
    cleanup_interval: 3600
    compression_enabled: true

# Search Engine Configurations
search:
  elasticsearch:
    enabled: false
    host: localhost
    port: 9200
    username: ""
    password: ""
    index_prefix: "dashboard_"
    number_of_shards: 1
    number_of_replicas: 1
    refresh_interval: "1s"
    ssl_enabled: false

  meilisearch:
    enabled: false
    host: localhost
    port: 7700
    api_key: ""
    index_prefix: "dashboard_"
    timeout: 5

# File Storage Configurations
storage:
  local:
    enabled: true
    base_path: "data/files/"
    allowed_extensions: [".csv", ".xlsx", ".xls", ".json", ".parquet"]
    max_file_size: "100mb"
    backup_enabled: true
    backup_path: "data/backups/files/"

  s3:
    enabled: false
    bucket: ""
    region: ""
    access_key: ""
    secret_key: ""
    endpoint: ""  # for custom S3-compatible storage
    prefix: "dashboard/"
    public_url: ""

# Data Processing Configurations
processing:
  chunk_size: 10000
  max_memory: "4gb"
  parallel_processes: 4
  temp_directory: "data/temp/"
  log_level: "INFO"

  compression:
    enabled: true
    algorithm: "gzip"  # gzip, bzip2, lz4
    level: 6

  validation:
    enabled: true
    max_rows: 1000000
    max_columns: 1000
    required_columns: []
    date_format: "%Y-%m-%d"
    null_values: ["", "NA", "NULL", "NaN"]

# Export Configurations
export:
  formats:
    - csv
    - excel
    - json
    - parquet
    - sql

  excel:
    engine: "openpyxl"
    sheet_name: "Data"
    date_format: "YYYY-MM-DD"
    float_format: "0.00"

  csv:
    delimiter: ","
    encoding: "utf-8"
    quoting: "minimal"
    date_format: "%Y-%m-%d"

  json:
    orient: "records"
    date_format: "iso"
    indent: 2

# Logging Configuration
logging:
  enabled: true
  path: "logs/"
  level: "INFO"
  max_size: "100mb"
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Monitoring Configuration
monitoring:
  enabled: true
  interval: 60  # seconds
  metrics:
    - cpu_usage
    - memory_usage
    - disk_usage
    - response_time
    - error_rate
  alerts:
    email:
      enabled: false
      smtp_host: ""
      smtp_port: 587
      username: ""
      password: ""
      from_address: ""
      to_addresses: []

# Security Configuration
security:
  encryption:
    enabled: true
    algorithm: "AES-256-GCM"
    key_file: "config/encryption.key"
    rotate_keys: false

  ssl:
    enabled: false
    cert_file: ""
    key_file: ""
    ca_file: ""

  cors:
    enabled: true
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]
    max_age: 3600

  rate_limiting:
    enabled: true
    rate: 100  # requests per minute
    burst: 200  # maximum burst size